### ISSUE TITLE
Default arguments are nonsense

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tf_server#2]
The Python client's transformPose-method defines the default target_time at rospy.Time(0), which is the zero time, so it is never possible to transform that far back in time. 

Rather: set None as the default and overwrite that with rospy.Time.now().

**Comment by reinzor** [comment]
For tf, time 0 means "the latest available" transform in the buffer. http://wiki.ros.org/tf/Tutorials/tf%20and%20Time%20(C++)

**Comment by LoyVanBeek** [comment]
I thought so as well, but then something else is wrong in the backend of this call.

**Comment by MatthijsBurgh** [comment]
@LoyVanBeek fixed or not?
