### ISSUE TITLE
Incosistent python API LookUpTransform

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tf_server#6]
Instead of returning a geometery_msgs/TransformStamped, both a list of transformation coordinates and rotation coordinates are returned, https://github.com/tue-robotics/tf_server/blob/10c5d70ab8eec2bf732b45c8722728f5857adf62/src/tf_server/tf_client.py#L92
While the other API's return a geometery_msgs/PoseStamped, https://github.com/tue-robotics/tf_server/blob/10c5d70ab8eec2bf732b45c8722728f5857adf62/src/tf_server/tf_client.py#L60,  and geometery_msgs/PointStamped, https://github.com/tue-robotics/tf_server/blob/10c5d70ab8eec2bf732b45c8722728f5857adf62/src/tf_server/tf_client.py#L44

**Comment by jlunenburg** [comment]
I don't get this point. AFAIK, the API of this class is exactly the same as that of a Python tf transformlistener. This way, you can use either a tf_client (if a tf_server is running) or a tf_listener. Changing this API will break this exchangability. Furthermore, you return messages if I understand correctly. Messages are for passing data and not for doing computations. Therefore, we've been getting rid of them throughout the code. 

So, unless I'm wrong in one of my assumptions I propose to close this issue and the corresponding pull requests.

**Comment by MatthijsBurgh** [comment]
You are correct. TF itself is inconsistent, because in C++ a TransformStamped is returned, while in python the translation and rotation are returned.
